name: ecommerce_module
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: 1.0.2
  flutter_riverpod:
  dio:
  dartz: 0.10.1
  shimmer:
  hive:
  carousel_slider:
  hive_flutter:
  go_router: 7.0.0
  pinput: 3.0.1
  badges: 3.1.2
  cached_network_image: 3.2.3
  flutter_screenutil: 5.9.0
  syncfusion_flutter_sliders: 23.1.36
  getwidget: 4.0.0
  flutter_rating_bar: 4.0.1
  percent_indicator: 4.2.3
  freezed_annotation: 2.4.1
  input_form_field:
    git:
      url: git@github.com:momshaddinury/input_form_field.git
      ref: version-0.0.6
  core:
    path: modules/core
  connectivity_plus: 5.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: 2.0.0
  build_runner: 2.3.2

  flutter_lints: 2.0.3
  lints: 2.1.1
  very_good_analysis: 5.1.0

flutter:

  uses-material-design: true

  assets:
    - images/
    - images/icons/
    - images/home_page_icons/
    - images/home_page_icons/category_icons/
    - images/banner/
    - images/product_detail_icons/
    - images/info_seller/

  fonts:
     - family: DM Sans
       fonts:
         - asset: fonts/DMSans-VariableFont_opsz,wght.ttf
           weight: 200